name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    if: ${{ github.repository == 'googleapis/common-protos-ruby' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ruby: "2.7"
          - os: ubuntu-latest
            ruby: "3.0"
          - os: ubuntu-latest
            ruby: "3.1"
          - os: ubuntu-latest
            ruby: "3.2"
          - os: ubuntu-latest
            ruby: "3.3"
          - os: macos-latest
            ruby: "3.3"
          - os: windows-latest
            ruby: "3.3"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
      - name: Checkout repo
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Checkout submodules
        run: |
          git submodule update --init
      - name: Install dependencies
        run: |
          gem install --no-document toys
      - name: Run CI
        run: |
          toys ci -v --build --test --github-event-name=${{ github.event_name }} --github-event-payload=${{ github.event_path }}
