name: Create New Gem
on:
  workflow_dispatch:
    inputs:
      protoPath:
        description: "The path to the protos"
        required: true
      args:
        description: "Extra command line arguments."
        required: false

jobs:
  NewGem:
    if: ${{ github.repository == 'googleapis/common-protos-ruby' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Install Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
      - name: Install tools
        run: "gem install --no-document toys grpc-tools:1.62.0"
      - name: execute
        run: |
          toys new-gem -v --fork ${GITHUB_EVENT_INPUTS_PROTOPATH} ${GITHUB_EVENT_INPUTS_ARGS}
        env:
          GITHUB_EVENT_INPUTS_PROTOPATH: ${{ github.event.inputs.protoPath }}
          GITHUB_EVENT_INPUTS_ARGS: ${{ github.event.inputs.args }}
