name: Update Gems
on:
  schedule:
    - cron: '43 11 * * 0'
  workflow_dispatch:
    inputs:
      args:
        description: "Extra command line arguments."
        required: false

jobs:
  generate-updates:
    if: ${{ github.repository == 'googleapis/common-protos-ruby' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - name: Install tools
        run: "gem install --no-document toys grpc-tools"
      - name: execute
        run: |
          toys update-gems-pr -v --fork ${{ github.event.inputs.args }}
